title: html-midi-player: MIDI player web component
description: HTML MIDI player is a web component for MIDI playback and visulation in the browser. You can use it to play MIDI files online.

github:
  is_project_page: true
  repository_name: html-midi-player
  repository_url: https://github.com/cifkao/html-midi-player
  owner_name: Ondřej Cífka
  owner_url: https://github.com/cifkao
  project_tagline: Play and display MIDI files on the web

theme: jekyll-theme-cayman

markdown: kramdown

plugins:
  - jekyll-seo-tag

defaults:
  - scope:
      path: ""
    values:
      layout: default

baseurl: /html-midi-player/

exclude:
  - assets/js
  - node_modules
  - vendor
  - Gemfile.lock
  - package.json
  - yarn.lock
  - yarn-error.log

keep_files:
  - assets/js
