name: Build

on:
  push:
    branches: [ www ]
  pull_request:
    branches: [ www ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install
      run: |
        cd $GITHUB_WORKSPACE
        yarn install

    - name: Build
      run: yarn build

    - name: Upload
      uses: actions/upload-artifact@v2
      with:
        name: dist
        path: dist/
